# Generated by Django 4.2.20 on 2025-09-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqs",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="aboutus",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="website/aboutus/"
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(upload_to="website/blogs/"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="image",
            field=models.ImageField(upload_to="website/testimonials/"),
        ),
        migrations.AlterField(
            model_name="testimonials",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
