# Generated by Django 4.2.20 on 2025-09-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Website",
            "0002_faqs_category_alter_aboutus_image_alter_blogs_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                (
                    "experience",
                    models.CharField(
                        help_text="Years of experience or experience description",
                        max_length=255,
                    ),
                ),
                (
                    "instagram_link",
                    models.URLField(
                        blank=True, help_text="Instagram profile URL", null=True
                    ),
                ),
                (
                    "facebook_link",
                    models.URLField(
                        blank=True, help_text="Facebook profile URL", null=True
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief biography", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Leadership",
                "ordering": ["order", "name"],
            },
        ),
    ]
