# Generated by Django 4.2.20 on 2025-09-05 08:12

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0003_leadership"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="author",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogs",
            name="category",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 9, 5, 8, 12, 23, 775010, tzinfo=datetime.timezone.utc
                ),
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogs",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogs",
            name="time_to_read",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
