# Generated by Django 4.2.20 on 2025-09-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0004_blogs_author_blogs_category_blogs_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="content",
            field=models.TextField(max_length=10000),
        ),
    ]
