# Generated by Django 4.2.20 on 2025-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0005_alter_blogs_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="relatedposts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="relatedposts/")),
                ("time_to_read", models.CharField(max_length=255)),
                ("content", models.TextField(max_length=10000)),
            ],
        ),
    ]
