# Generated by Django 4.2.20 on 2025-09-05 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0006_relatedposts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs",
            old_name="content",
            new_name="description_1",
        ),
        migrations.AddField(
            model_name="blogs",
            name="description_2",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="blogs",
            name="quote",
            field=models.TextField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
