# Generated by Django 4.2.20 on 2025-09-05 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0007_rename_content_blogs_description_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relatedposts",
            old_name="content",
            new_name="description_1",
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="description_2",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="quote",
            field=models.TextField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="relatedposts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="relatedposts",
            name="time_to_read",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
