# Generated by Django 4.2.20 on 2025-09-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0008_rename_content_relatedposts_description_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
