# Generated by Django 4.2.20 on 2025-09-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0009_alter_aboutus_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsandconditions",
            name="heading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="subheading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="terms_and_conditions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
