# Generated by Django 4.2.20 on 2025-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0010_alter_termsandconditions_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacypolicy",
            name="content",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="heading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="privacy_policy",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="subheading",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
