# Generated by Django 4.2.20 on 2025-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0011_alter_privacypolicy_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="website/pdfs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="website/videos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="stayconnected",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
