# Generated by Django 4.2.20 on 2025-09-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0012_downloadpdf_video_stayconnected_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadpdf",
            name="pdf",
        ),
    ]
