# Generated by Django 4.2.20 on 2025-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0013_remove_downloadpdf_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadpdf",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
