# Generated by Django 4.2.20 on 2025-09-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0014_downloadpdf_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="platforms",
            old_name="facebook",
            new_name="Facebook",
        ),
        migrations.RenameField(
            model_name="platforms",
            old_name="instagram",
            new_name="Instagram",
        ),
        migrations.RenameField(
            model_name="platforms",
            old_name="pinterest",
            new_name="LinkedIn",
        ),
        migrations.RenameField(
            model_name="platforms",
            old_name="twitter",
            new_name="TikTok",
        ),
    ]
