# Generated by Django 4.2.27 on 2026-01-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_rename_facebook_platforms_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='experience',
            field=models.CharField(blank=True, help_text='Years of experience or experience description', max_length=255, null=True),
        ),
    ]
