# Generated by Django 4.2.27 on 2026-01-13 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0016_alter_leadership_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True, help_text='Author biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='website/authors/')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description for SEO')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-publish_date', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Main content body - supports HTML/rich text'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if this content exists elsewhere'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Short summary for listing pages, search results, and social sharing (max 500 chars)', max_length=500),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_alt_text',
            field=models.CharField(blank=True, default='', help_text='Alt text for accessibility (recommended for SEO and screen readers)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Optional caption displayed below the image', max_length=500),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_credit',
            field=models.CharField(blank=True, help_text='Photo credit / source attribution', max_length=255),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this post on homepage/listings'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin to top of blog listing'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated on save'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars). Defaults to excerpt if blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 chars). Defaults to post title if blank.', max_length=70),
        ),
        migrations.AddField(
            model_name='blogs',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (max 200 chars)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogs',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Custom image for social sharing (1200x630px recommended). Uses featured image if blank.', null=True, upload_to='website/blogs/og/'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing (max 95 chars)', max_length=95),
        ),
        migrations.AddField(
            model_name='blogs',
            name='preview_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token for shareable preview links'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='When the post should be published (timezone-aware)', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='pull_quote',
            field=models.TextField(blank=True, help_text='Optional highlighted quote to display prominently', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated from body content. Override only if needed.', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='related_posts',
            field=models.ManyToManyField(blank=True, help_text='Manually select related posts', to='Website.blogs'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='robots_indexable',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated if blank)', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publishing status of the post', max_length=20),
        ),
        migrations.AddField(
            model_name='blogs',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description (optional)', max_length=200),
        ),
        migrations.AddField(
            model_name='blogs',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title (optional)', max_length=70),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.CharField(blank=True, help_text="DEPRECATED: Use 'author_entity' instead", max_length=255),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(blank=True, help_text="DEPRECATED: Use 'category_new' FK instead", max_length=255),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(blank=True, help_text="DEPRECATED: Use 'publish_date' instead", null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description_1',
            field=models.TextField(blank=True, help_text="DEPRECATED: Use 'body' field instead", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description_2',
            field=models.TextField(blank=True, help_text="DEPRECATED: Use 'body' field instead", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='website/blogs/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='quote',
            field=models.TextField(blank=True, help_text="DEPRECATED: Use 'pull_quote' field instead", max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time_to_read',
            field=models.CharField(blank=True, help_text="DEPRECATED: Use 'reading_time_minutes' instead", max_length=255),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(help_text='The main headline of the blog post', max_length=255),
        ),
        migrations.CreateModel(
            name='HistoricalBlogs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='The main headline of the blog post', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated if blank)', max_length=255)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short summary for listing pages, search results, and social sharing (max 500 chars)', max_length=500)),
                ('body', models.TextField(blank=True, default='', help_text='Main content body - supports HTML/rich text')),
                ('pull_quote', models.TextField(blank=True, help_text='Optional highlighted quote to display prominently', null=True)),
                ('description_1', models.TextField(blank=True, help_text="DEPRECATED: Use 'body' field instead", max_length=10000, null=True)),
                ('description_2', models.TextField(blank=True, help_text="DEPRECATED: Use 'body' field instead", max_length=10000, null=True)),
                ('quote', models.TextField(blank=True, help_text="DEPRECATED: Use 'pull_quote' field instead", max_length=10000, null=True)),
                ('image', models.TextField(blank=True, help_text='Featured image for the blog post', max_length=100, null=True)),
                ('image_alt_text', models.CharField(blank=True, default='', help_text='Alt text for accessibility (recommended for SEO and screen readers)', max_length=255)),
                ('image_caption', models.CharField(blank=True, help_text='Optional caption displayed below the image', max_length=500)),
                ('image_credit', models.CharField(blank=True, help_text='Photo credit / source attribution', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publishing status of the post', max_length=20)),
                ('publish_date', models.DateTimeField(blank=True, help_text='When the post should be published (timezone-aware)', null=True)),
                ('last_modified', models.DateTimeField(blank=True, editable=False, help_text='Automatically updated on save')),
                ('preview_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token for shareable preview links')),
                ('date', models.DateField(blank=True, help_text="DEPRECATED: Use 'publish_date' instead", null=True)),
                ('author', models.CharField(blank=True, help_text="DEPRECATED: Use 'author_entity' instead", max_length=255)),
                ('category', models.CharField(blank=True, help_text="DEPRECATED: Use 'category_new' FK instead", max_length=255)),
                ('reading_time_minutes', models.PositiveIntegerField(blank=True, help_text='Auto-calculated from body content. Override only if needed.', null=True)),
                ('time_to_read', models.CharField(blank=True, help_text="DEPRECATED: Use 'reading_time_minutes' instead", max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars). Defaults to post title if blank.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars). Defaults to excerpt if blank.', max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if this content exists elsewhere')),
                ('robots_indexable', models.BooleanField(default=True, help_text='Allow search engines to index this page')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing (max 95 chars)', max_length=95)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description (max 200 chars)', max_length=200)),
                ('og_image', models.TextField(blank=True, help_text='Custom image for social sharing (1200x630px recommended). Uses featured image if blank.', max_length=100, null=True)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter card title (optional)', max_length=70)),
                ('twitter_description', models.CharField(blank=True, help_text='Twitter card description (optional)', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post on homepage/listings')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to top of blog listing')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author_entity', models.ForeignKey(blank=True, db_constraint=False, help_text='Select from registered authors', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Website.blogauthor')),
                ('category_new', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary category for this post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Website.blogcategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Blog Post',
                'verbose_name_plural': 'historical Blog Posts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='blogs',
            name='author_entity',
            field=models.ForeignKey(blank=True, help_text='Select from registered authors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='Website.blogauthor'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='category_new',
            field=models.ForeignKey(blank=True, help_text='Primary category for this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='Website.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Add multiple tags for better discoverability', related_name='blog_posts', to='Website.blogtag'),
        ),
    ]
