# Generated by Django 4.2.27 on 2026-01-13 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0017_blogauthor_blogcategory_blogtag_alter_blogs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='body_html',
            field=models.TextField(blank=True, default='', help_text='Auto-generated sanitized HTML from raw_draft. DO NOT EDIT directly.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='Hash of raw_draft to detect changes', max_length=64),
        ),
        migrations.AddField(
            model_name='blogs',
            name='entities_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted entities (people, orgs, concepts) for internal linking'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='excerpt_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='extracted_faqs_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted FAQ items from content'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='key_facts',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted verifiable claims/facts for high-risk content validation.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='key_sections_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted content sections for reuse'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='key_takeaways',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted key points. Edit to customize.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='key_takeaways_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, help_text='When the Brita pipeline last processed this post', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_description_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='meta_title_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='notes_private',
            field=models.TextField(blank=True, default='', help_text='Private notes (never published). For internal communication, research notes, etc.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='raw_draft',
            field=models.TextField(blank=True, default='', help_text='Markdown content - the ONLY required writing field. Pour in your raw narrative here.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='requires_compliance_review',
            field=models.BooleanField(default=False, help_text='Flag for content requiring legal/compliance review before publish'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Reviewer notes and feedback'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the post was reviewed/approved', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewer who approved this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogs',
            name='robots_followable',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='schema_type',
            field=models.CharField(blank=True, default='BlogPosting', help_text='Schema.org type (Article, BlogPosting, NewsArticle, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='blogs',
            name='slug_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='social_copy_linkedin',
            field=models.TextField(blank=True, default='', help_text='Auto-generated LinkedIn post copy. Override to customize.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='social_copy_linkedin_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='social_copy_twitter',
            field=models.CharField(blank=True, default='', help_text='Auto-generated Twitter/X post copy (<= 280 chars). Override to customize.', max_length=280),
        ),
        migrations.AddField(
            model_name='blogs',
            name='social_copy_twitter_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='social_hashtags',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated hashtags (3-8). Override to customize.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='social_hashtags_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='sources_json',
            field=models.JSONField(blank=True, default=list, help_text='Citations and sources referenced in this post [{url, label, accessed_date}]'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='summary_for_llms',
            field=models.TextField(blank=True, default='', help_text='Auto-generated tight, factual summary (80-120 words) for LLM consumption.'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='summary_for_llms_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='toc_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated table of contents as JSON'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Current publish-blocking errors'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list, help_text='Current publish warnings (non-blocking)'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated word count', null=True),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='body_html',
            field=models.TextField(blank=True, default='', help_text='Auto-generated sanitized HTML from raw_draft. DO NOT EDIT directly.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='Hash of raw_draft to detect changes', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='entities_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted entities (people, orgs, concepts) for internal linking'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='excerpt_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='extracted_faqs_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted FAQ items from content'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='key_facts',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted verifiable claims/facts for high-risk content validation.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='key_sections_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted content sections for reuse'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='key_takeaways',
            field=models.JSONField(blank=True, default=list, help_text='Auto-extracted key points. Edit to customize.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='key_takeaways_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, help_text='When the Brita pipeline last processed this post', null=True),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='meta_description_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='meta_title_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='notes_private',
            field=models.TextField(blank=True, default='', help_text='Private notes (never published). For internal communication, research notes, etc.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='raw_draft',
            field=models.TextField(blank=True, default='', help_text='Markdown content - the ONLY required writing field. Pour in your raw narrative here.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='requires_compliance_review',
            field=models.BooleanField(default=False, help_text='Flag for content requiring legal/compliance review before publish'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Reviewer notes and feedback'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the post was reviewed/approved', null=True),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Reviewer who approved this post', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='robots_followable',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links on this page'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='schema_type',
            field=models.CharField(blank=True, default='BlogPosting', help_text='Schema.org type (Article, BlogPosting, NewsArticle, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='slug_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='social_copy_linkedin',
            field=models.TextField(blank=True, default='', help_text='Auto-generated LinkedIn post copy. Override to customize.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='social_copy_linkedin_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='social_copy_twitter',
            field=models.CharField(blank=True, default='', help_text='Auto-generated Twitter/X post copy (<= 280 chars). Override to customize.', max_length=280),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='social_copy_twitter_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='social_hashtags',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated hashtags (3-8). Override to customize.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='social_hashtags_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='sources_json',
            field=models.JSONField(blank=True, default=list, help_text='Citations and sources referenced in this post [{url, label, accessed_date}]'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='summary_for_llms',
            field=models.TextField(blank=True, default='', help_text='Auto-generated tight, factual summary (80-120 words) for LLM consumption.'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='summary_for_llms_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='title_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-update'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='toc_json',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated table of contents as JSON'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='Current publish-blocking errors'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='validation_warnings',
            field=models.JSONField(blank=True, default=list, help_text='Current publish warnings (non-blocking)'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated word count', null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: Use raw_draft instead. Auto-synced from body_html.'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL. Defaults to current URL if blank.'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Auto-generated 155-180 char summary. Override to customize.', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Auto-generated SEO description (<= 160 chars). Override to customize.', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Auto-generated SEO title (<= 60 chars). Override to customize.', max_length=70),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated from body content (200 wpm).', null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title. Override to customize.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publishing status of the post', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from first H1. Override to customize.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='body',
            field=models.TextField(blank=True, default='', help_text='DEPRECATED: Use raw_draft instead. Auto-synced from body_html.'),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL. Defaults to current URL if blank.'),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Auto-generated 155-180 char summary. Override to customize.', max_length=500),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Auto-generated SEO description (<= 160 chars). Override to customize.', max_length=160),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Auto-generated SEO title (<= 60 chars). Override to customize.', max_length=70),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated from body content (200 wpm).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title. Override to customize.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publishing status of the post', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-generated from first H1. Override to customize.', max_length=255),
        ),
    ]
