# Generated by Django 4.2.27 on 2026-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_brita_filter_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='reading_time_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-recalculation of reading time'),
        ),
        migrations.AddField(
            model_name='historicalblogs',
            name='reading_time_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent auto-recalculation of reading time'),
        ),
    ]
