# Generated by Django 4.2.27 on 2026-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_blogs_reading_time_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated from body content (200 wpm). Set manually to override.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalblogs',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated from body content (200 wpm). Set manually to override.', null=True),
        ),
    ]
