# Generated by Django 4.2.27 on 2026-01-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_reading_time_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadpdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='website/pdfs/'),
        ),
        migrations.AlterField(
            model_name='downloadpdf',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
