# Generated by Django 4.2.20 on 2025-07-10 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foodinfo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Choice"),
                            ("multiple", "Multiple Choice"),
                        ],
                        default="single",
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diet", "Dietary Preference"),
                            ("health", "Health Condition"),
                            ("allergy", "Allergy"),
                            ("primary health goals", "Health Goals"),
                            ("Parental status", "Parental status"),
                            ("safer meal planning", "Family_Health_Awareness"),
                            (
                                "quality and safety of ingredients",
                                "Emotional_Conection",
                            ),
                            ("negative health symptoms", "Health_impact_awareness"),
                            ("achive by using IngredientIQ", "Desired_outcome"),
                            ("ready to take control of health", "Motivation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_super_admin", models.BooleanField(default=True)),
                (
                    "admin_permissions",
                    models.JSONField(
                        default=dict, help_text="Stores admin-specific permissions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Super Admin",
                "verbose_name_plural": "Super Admins",
            },
            bases=("foodinfo.user",),
        ),
        migrations.CreateModel(
            name="OnboardingChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="panel.onboardingquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="panel.onboardingquestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
