# Generated by Django 4.2.20 on 2025-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.CharField(choices=[('profile_demographics', 'Profile & Demographics'), ('motivation_cognitive', 'Motivation & Cognitive Profile'), ('medical_clinical', 'Medical & Clinical History'), ('medications_supplements', 'Medications & Supplements'), ('allergies_sensitivities', 'Allergies & Sensitivities'), ('lifestyle_dietary', 'Lifestyle & Dietary Preferences'), ('behavioral_rhythm', 'Behavioral Rhythm & Feedback Cadence')], max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('purpose', models.TextField(help_text='What this category feeds into the AI system')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Category',
                'verbose_name_plural': 'Onboarding Categories',
                'ordering': ['order', 'category_name'],
            },
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='category',
            field=models.CharField(choices=[('profile_demographics', 'Profile & Demographics'), ('motivation_cognitive', 'Motivation & Cognitive Profile'), ('medical_clinical', 'Medical & Clinical History'), ('medications_supplements', 'Medications & Supplements'), ('allergies_sensitivities', 'Allergies & Sensitivities'), ('lifestyle_dietary', 'Lifestyle & Dietary Preferences'), ('behavioral_rhythm', 'Behavioral Rhythm & Feedback Cadence'), ('diet', 'Dietary Preference'), ('health', 'Health Condition'), ('allergy', 'Allergy'), ('primary health goals', 'Health Goals'), ('Parental status', 'Parental status'), ('safer meal planning', 'Family_Health_Awareness'), ('quality and safety of ingredients', 'Emotional_Conection'), ('negative health symptoms', 'Health_impact_awareness'), ('achive by using IngredientIQ', 'Desired_outcome'), ('ready to take control of health', 'Motivation'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
