# Generated by Django 4.2.20 on 2025-07-10 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("otp", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Dietary_preferences",
                    models.TextField(
                        blank=True,
                        help_text="Dietary preferences (e.g., vegan, keto).",
                        null=True,
                    ),
                ),
                (
                    "Health_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Medical conditions (e.g., diabetes, hypertension).",
                        null=True,
                    ),
                ),
                (
                    "Allergies",
                    models.TextField(
                        blank=True,
                        help_text="Medical conditions (e.g., vegan, gluten).",
                        null=True,
                    ),
                ),
                ("Health_Goals", models.TextField(blank=True, null=True)),
                ("Parental_status", models.TextField(blank=True, null=True)),
                ("Family_Health_Awareness", models.TextField(blank=True, null=True)),
                ("Emotional_Conection", models.TextField(blank=True, null=True)),
                ("Health_impact_awareness", models.TextField(blank=True, null=True)),
                ("Desired_outcome", models.TextField(blank=True, null=True)),
                ("Motivation", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_2fa_enabled",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("is_staff", models.BooleanField(default=True)),
                ("is_terms", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            7,
                            10,
                            17,
                            55,
                            15,
                            381272,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("dark_mode", models.BooleanField(default=False)),
                ("language", models.CharField(default="English", max_length=20)),
                (
                    "subscription_plan",
                    models.CharField(default="Freemium plan", max_length=100),
                ),
                ("has_answered_onboarding", models.BooleanField(default=False)),
                ("privacy_settings_enabled", models.BooleanField(default=True)),
                ("loves_app", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AboutUS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("customer_support", "Customer Support"),
                            ("technical_support", "Technical Support"),
                            ("billing", "Billing"),
                            ("general", "General Inquiries"),
                            ("partnership", "Partnership"),
                            ("media", "Media Relations"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "available_hours",
                    models.CharField(
                        default="Monday-Friday, 9 AM - 6 PM", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="privacypolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Termandcondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        choices=[("freemium", "Freemium"), ("premium", "Premium")],
                        max_length=50,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="inactive", max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserHealthPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preference_type",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("dietary", "Dietary Preference"),
                            ("medical", "Medical History"),
                        ],
                        help_text="Type of health preference.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the allergen, dietary preference, or medical condition (e.g., peanuts, vegan, diabetes).",
                        max_length=100,
                    ),
                ),
                (
                    "threshold",
                    models.CharField(
                        help_text="Compulsory threshold value (with units) that the user can tolerate. Enter 0 (or 0 with unit, e.g., 0mg) if none.",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_customer_id", models.CharField(max_length=255, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodLabelScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("product_image_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField()),
                ("extracted_text", models.TextField()),
                ("nutrition_data", models.JSONField()),
                ("safety_status", models.CharField(max_length=20)),
                (
                    "flagged_ingredients",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
