# Generated by Django 4.2.20 on 2025-07-11 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0002_usersubscription_premium_type_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 11, 8, 28, 12, 346152, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
