# Generated by Django 4.2.20 on 2025-08-18 18:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0003_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 18, 18, 38, 52, 970260, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="MonthlyScanUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("scan_count", models.IntegerField(default=0)),
                ("premium_scans_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "year", "month"],
                        name="foodinfo_mo_user_id_e9a9db_idx",
                    )
                ],
                "unique_together": {("user", "year", "month")},
            },
        ),
    ]
