# Generated by Django 4.2.20 on 2025-08-25 06:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0004_alter_user_created_at_monthlyscanusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 25, 6, 20, 43, 694365, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
