# Generated by Django 4.2.20 on 2025-08-26 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0006_notificationtemplate_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="app_store_transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="google_play_purchase_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="platform",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe/Web"),
                    ("ios", "iOS App Store"),
                    ("android", "Google Play"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 26, 6, 57, 35, 550595, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("past_due", "Past Due"),
                    ("unpaid", "Unpaid"),
                    ("pending_cancel", "Pending Cancel"),
                    ("inactive", "Inactive"),
                ],
                default="inactive",
                max_length=50,
            ),
        ),
    ]
