# Generated by Django 4.2.20 on 2025-08-31 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0007_usersubscription_app_store_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 8, 31, 7, 43, 58, 897139, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
