# Generated by Django 4.2.20 on 2025-09-01 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0008_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 1, 10, 30, 18, 739448, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
