# Generated by Django 4.2.20 on 2025-09-05 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0009_alter_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_login_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="social_login_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("welcome", "Welcome Message"),
                    ("subscription_purchased", "Subscription Purchased"),
                    ("subscription_expiring", "Subscription Expiring"),
                    ("subscription_expired", "Subscription Expired"),
                    ("subscription_cancelled", "Subscription Cancelled"),
                    ("subscription_upgraded", "Subscription Upgraded"),
                    ("subscription_downgraded", "Subscription Downgraded"),
                    ("limit_warning", "Limit Warning"),
                    ("app_update", "App Update Available"),
                    ("feature_reminder", "Feature Reminder"),
                    ("promotional", "Promotional"),
                    ("engagement", "Engagement"),
                    ("custom", "Custom Notification"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 5, 7, 22, 17, 257323, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
