# Generated by Django 4.2.20 on 2025-09-05 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0010_user_device_token_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 5, 7, 42, 37, 806451, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
