# Generated by Django 4.2.20 on 2025-09-05 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0016_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 5, 12, 45, 31, 396356, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
