# Generated by Django 4.2.20 on 2025-09-11 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0018_alter_user_created_at_accountdeletionrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 6, 46, 21, 568366, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
