# Generated by Django 4.2.20 on 2025-09-11 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0019_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 7, 23, 29, 235451, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
