# Generated by Django 4.2.20 on 2025-09-11 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0023_alter_faq_category_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 11, 12, 3, 59, 59062, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
