# Generated by Django 4.2.20 on 2025-09-15 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0024_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 15, 10, 42, 17, 473392, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
