# Generated by Django 4.2.20 on 2025-09-19 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0026_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 19, 5, 8, 44, 423515, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
