# Generated by Django 4.2.20 on 2025-09-23 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0027_alter_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_notifications_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 23, 8, 12, 6, 595528, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
