# Generated by Django 4.2.20 on 2025-09-23 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0028_user_subscription_notifications_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_deactivation_date",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_deactivation",
                to="foodinfo.accountdeletionrequest",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 23, 9, 56, 39, 797231, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
