# Generated by Django 4.2.20 on 2025-09-25 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0030_downloadpdf_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 7, 29, 14, 123487, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="download_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_download",
                to="foodinfo.downloadpdf",
            ),
        ),
    ]
