# Generated by Django 4.2.20 on 2025-09-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0032_alter_user_created_at_alter_user_download_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 7, 30, 36, 23563, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
