# Generated by Django 4.2.20 on 2025-09-25 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0033_alter_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadpdf",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="downloadpdf",
            name="email",
        ),
        migrations.RemoveField(
            model_name="downloadpdf",
            name="name",
        ),
        migrations.RemoveField(
            model_name="downloadpdf",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="downloadpdf",
            name="download_data",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 7, 46, 20, 820171, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
