# Generated by Django 4.2.20 on 2025-09-25 07:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0034_remove_downloadpdf_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadpdf",
            name="download_data",
        ),
        migrations.AddField(
            model_name="downloadpdf",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="downloadpdf",
            name="download_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="downloadpdf",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="downloadpdf",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="downloadpdf",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 7, 52, 33, 773797, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
