# Generated by Django 4.2.20 on 2025-09-25 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0035_remove_downloadpdf_download_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 25, 8, 21, 20, 176298, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
