# Generated by Django 4.2.20 on 2025-10-07 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0036_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='downloadpdf',
            options={'verbose_name': 'Data Download Request', 'verbose_name_plural': 'Data Download Requests'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 11, 24, 5, 94094, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='downloadpdf',
            name='download_requested',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_pdf', to='foodinfo.downloadrequest'),
        ),
    ]
