# Generated by Django 4.2.20 on 2025-10-07 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0037_downloadrequest_alter_downloadpdf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 12, 19, 45, 543593, tzinfo=datetime.timezone.utc)),
        ),
    ]
