# Generated by Django 4.2.20 on 2025-10-07 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0040_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 12, 23, 33, 287417, tzinfo=datetime.timezone.utc)),
        ),
    ]
