# Generated by Django 4.2.20 on 2025-10-07 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0042_create_downloadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 12, 28, 47, 878128, tzinfo=datetime.timezone.utc)),
        ),
    ]
