# Generated by Django 4.2.20 on 2025-10-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0044_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadpdf',
            name='download_requested',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_pdf', to='foodinfo.downloadrequest'),
        ),
    ]
