# Generated by Django 4.2.20 on 2025-10-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0044_alter_user_created_at'),
    ]

    operations = [
        # No-op: the `download_requested` relation is introduced in
        # foodinfo.0037 in a Postgres-safe way (avoids boolean->bigint casts).
    ]
