# Generated by Django 4.2.20 on 2025-10-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0048_fix_foreign_key_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 16, 29, 29, 741027, tzinfo=datetime.timezone.utc)),
        ),
    ]
