# Generated by Django 4.2.20 on 2025-10-28 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0049_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 12, 18, 20, 275845, tzinfo=datetime.timezone.utc)),
        ),
    ]
