# Generated by Django 4.2.20 on 2025-10-29 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0050_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Behavioral_patterns',
            field=models.TextField(blank=True, help_text='Behavioral rhythm and feedback cadence data', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Demographics',
            field=models.TextField(blank=True, help_text='Profile & Demographics data (age, sex, height, region)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Medications',
            field=models.TextField(blank=True, help_text='Medications and supplements information', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 10, 22, 0, 556513, tzinfo=datetime.timezone.utc)),
        ),
    ]
