# Generated by Django 4.2.20 on 2025-10-30 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0051_user_behavioral_patterns_user_demographics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 12, 42, 37, 95594, tzinfo=datetime.timezone.utc)),
        ),
    ]
