# Generated by Django 4.2.20 on 2025-11-13 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodinfo", "0052_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 11, 13, 17, 39, 34, 114862, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
