# Generated by Django 4.2.20 on 2025-04-14 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodinfo', '0013_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlabelscan',
            name='product_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 12, 45, 18, 417051, tzinfo=datetime.timezone.utc)),
        ),
    ]
