"""
Django settings for foodanalysis project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'foodinfo.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e)m3@n3vazo2!0l!xo%j1ov+=8q##%9d(*xq3!mu2j=raw!u24'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','18.188.184.213','54.160.233.148','ingredientiq.ai','172.16.100.214','fab492fa03e4.ngrok-free.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'foodinfo',
    'storages',
    # 'social_django'
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'panel',
    'corsheaders',
    'Website',
    # 'django_celery_beat',  # Uncomment if using Celery for background tasks
    # 'foodinfo.apps.YourAppConfig',
]

SITE_ID = 1 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Move CORS to top
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'foodanalysis.middleware.SecurityHeadersMiddleware',  # Custom security headers
    'foodanalysis.middleware.StaticFileMIMEMiddleware',  # Custom MIME type handling
]

ROOT_URLCONF = 'foodanalysis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'foodanalysis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("POSTGRES_DB", "foodai"),
#         "USER": os.getenv("POSTGRES_USER", "foodai_user"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "pass098foodai1123"),
#         "HOST": os.getenv("DB_HOST", "foodai-db"),
#         "PORT": os.getenv("DB_PORT", "5432"),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/



BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'build', 'static'),
    os.path.join(BASE_DIR, 'react_admin', 'static'),        
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
load_dotenv() 
import ssl
import certifi
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.hostnet.nl'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'support@serviceconnect.nl'     # replace with your actual email
# EMAIL_HOST_PASSWORD = 'gB;@-H6BcF@tNh?' # replace with actual password
# DEFAULT_FROM_EMAIL = 'AI IngredientIQ <support@serviceconnect.nl>'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = False
# EMAIL_SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_HOST_USER = 'kajalmittalkm62@gmail.com' # Your Gmail Address
# EMAIL_HOST_PASSWORD = 'pifq dehh aaca asey' # App password (not your Gmail password)



# CORS_ALLOWED_ORIGINS = ['']
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]

# Security headers for CORS and COOP
SECURE_CROSS_ORIGIN_OPENER_POLICY = None  # Allow COOP to be set by middleware
CORS_EXPOSE_HEADERS = [
    'Cross-Origin-Opener-Policy',
    'Cross-Origin-Embedder-Policy',
]

# Additional security settings
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=7),  # Adjust as needed, e.g., 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Adjust as needed, e.g., 7 days
    # Other settings...
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


AWS_ACCESS_KEY_ID=os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY=os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME=os.getenv("AWS_STORAGE_BUCKET_NAME", "ingredientiq")
AWS_S3_REGION_NAME=os.getenv("AWS_S3_REGION_NAME", "us-east-2")
AWS_S3_CUSTOM_DOMAIN=os.getenv("AWS_S3_CUSTOM_DOMAIN", "ingredientiq.s3.us-east-2.amazonaws.com")
DEFAULT_FILE_STORAGE = os.getenv("DEFAULT_FILE_STORAGE", "storages.backends.s3boto3.S3Boto3Storage")
AWS_DEFAULT_ACL = None  # Disable ACL to avoid bucket compatibility issues
AWS_S3_URL_PROTOCOL =os.getenv("AWS_S3_URL_PROTOCOL", "https")
AWS_S3_USE_SSL = True
AWS_S3_VERIFY = True
AWS_S3_ADDRESSING_STYLE = 'virtual'
AWS_S3_SIGNATURE_VERSION = 's3v4'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.apple.AppleIdAuth',
    'django.contrib.auth.backends.ModelBackend',
)



SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

SOCIAL_AUTH_FACEBOOK_KEY = os.getenv("SOCIAL_AUTH_FACEBOOK_KEY")
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv("SOCIAL_AUTH_FACEBOOK_SECRET")

SOCIAL_AUTH_APPLE_ID_CLIENT = os.getenv("SOCIAL_AUTH_APPLE_ID_CLIENT")
SOCIAL_AUTH_APPLE_ID_TEAM = os.getenv("SOCIAL_AUTH_APPLE_ID_TEAM")
SOCIAL_AUTH_APPLE_ID_SECRET = os.getenv("SOCIAL_AUTH_APPLE_ID_SECRET")
SOCIAL_AUTH_APPLE_ID_SECRET_KEY = os.getenv("SOCIAL_AUTH_APPLE_ID_SECRET_KEY")
SOCIAL_AUTH_APPLE_ID_SECRET_FILE = os.getenv("SOCIAL_AUTH_APPLE_ID_SECRET_FILE")


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('Client_ID'),
            'secret': os.getenv('secret'),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {
            'access_type': 'offline',
        }
    }
}

# Django Allauth settings (updated to use new format)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None # Avoid looking for 'username'
ACCOUNT_SIGNUP_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'


STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_MONTHLY_PRICE_ID = "price_1RCJv1Qu1wso2WoQmk9rp5J4"
STRIPE_MONTHLY_DISCOUNTED_PRICE_ID = os.getenv("STRIPE_MONTHLY_DISCOUNTED_PRICE_ID", "price_1S2F1aQu1wso2WoQc6dJkXvv")  # 50% off price ID
STRIPE_YEARLY_PRICE_ID = os.getenv("STRIPE_YEARLY_PRICE_ID")
STRIPE_YEARLY_DISCOUNTED_PRICE_ID = os.getenv("STRIPE_YEARLY_DISCOUNTED_PRICE_ID","price_1S25S8Qu1wso2WoQquwNlfqx")  # 50% off yearly price ID
STRIPE_WEBHOOK_SECRET  = os.getenv("STRIPE_WEBHOOK_SECRET ")

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")

CORS_ALLOWED_ORIGINS = [
    "http://18.188.184.213:8018",
    "http://54.160.233.148:8888",
    "https://ingredientiq.ai",
    "http://172.16.100.214",
    "https://fab492fa03e4.ngrok-free.app",
    "http://127.0.0.1:8022",
    "http://localhost:8022",
]

CSRF_TRUSTED_ORIGINS = [
    "http://54.160.233.148:8888",
    "https://ingredientiq.ai",
    "http://18.188.184.213:8018",
    "https://18.188.184.213:8018",
    "http://54.160.233.148:8081",
    "https://fab492fa03e4.ngrok-free.app",
    "http://127.0.0.1:8022",
    "http://localhost:8022",
    "https://fcf13a9f777b.ngrok-free.app"
]

# Firebase Configuration
FIREBASE_CREDENTIALS_PATH = os.getenv("FIREBASE_CREDENTIALS_PATH", "ai-ingredients-3a169-firebase-adminsdk-fbsvc-0b7720be4a.json")

# Celery Configuration (Optional - for background tasks)
# Uncomment and configure if you want to use Celery for background tasks
# CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Configuration (Optional)
# from celery.schedules import crontab
# CELERY_BEAT_SCHEDULE = {
#     'check-subscription-expiry': {
#         'task': 'foodinfo.tasks.check_subscription_expiry_task',
#         'schedule': crontab(hour=9, minute=0),  # Daily at 9 AM
#     },
#     'send-app-update-notifications': {
#         'task': 'foodinfo.tasks.send_app_update_notifications_task',
#         'schedule': crontab(hour=10, minute=0, day_of_week=1),  # Weekly on Monday at 10 AM
#     },
# }
USDA_API_KEY = os.getenv("USDA_API_KEY")

# Google Custom Search API for blog search
GOOGLE_CUSTOM_SEARCH_ENGINE_ID="a2e3976c052734bb6"
GOOGLE_CUSTOM_SEARCH_API_KEY = "AIzaSyA1CElXL4vN8KxaPgEw0NGqWJGzuWZecm4"

# YouTube Data API for video search
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")